name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          BIN_NAME=aws-ssm-connect
          OUT_NAME=aws-ssm-connect-${GOOS}-${GOARCH}
          VERSION=${GITHUB_REF##*/}  # Extracts the tag name like 'v0.0.4'
          GOOS=${GOOS} GOARCH=${GOARCH} CGO_ENABLED=0 \
          go build -ldflags "-X github.com/ilkerispir/aws-ssm-connect/cmd.Version=$VERSION" -o dist/${BIN_NAME}
          tar -czf dist/${OUT_NAME}.tar.gz -C dist ${BIN_NAME}
          rm dist/${BIN_NAME}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*.tar.gz

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
